import type {
  TABLE_FERTILIZERS,
  TABLE_PIVOT_FERTILIZER_WATERING_SCHEMA,
  TABLE_PLANT_IMAGES,
  TABLE_PLANT_PHASES,
  TABLE_PLANT_SUBSTRATES,
  TABLE_PLANT_WATERING_LOGS,
  TABLE_PLANTS,
  TABLE_WATERING_SCHEMAS,
} from '../db'

interface ImportExportData {
  [TABLE_PLANTS]: Array<any>
  [TABLE_PLANT_IMAGES]: Array<any>
  [TABLE_PLANT_SUBSTRATES]: Array<any>
  [TABLE_PLANT_PHASES]: Array<any>
  [TABLE_PLANT_WATERING_LOGS]: Array<any>
  [TABLE_FERTILIZERS]: Array<any>
  [TABLE_WATERING_SCHEMAS]: Array<any>
  [TABLE_PIVOT_FERTILIZER_WATERING_SCHEMA]: Array<any>
}

type BackupStoreNames = typeof TABLE_PLANTS
  | typeof TABLE_PLANT_IMAGES
  | typeof TABLE_PLANT_SUBSTRATES
  | typeof TABLE_PLANT_PHASES
  | typeof TABLE_PLANT_WATERING_LOGS
  | typeof TABLE_FERTILIZERS
  | typeof TABLE_WATERING_SCHEMAS
  | typeof TABLE_PIVOT_FERTILIZER_WATERING_SCHEMA

type BackupTxStores = BackupStoreNames[]
